### Face Detection 👦🏻 👧🏻 

In [1]:
import cv2

Create a `Cascade Classifier` Object
- Contains `Features` of a Face

In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

`Read` the Image

In [3]:
img = cv2.imread('../Image/GuidoVanRossum.jpg')

`Convert` the Image as `Gray Scale Image`

In [4]:
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

`Search` for Face `Rectangle Coordinates`

In [5]:
face = face_cascade.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors=5)

for x, y, w, h in face:
    img = cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0), 3)
        
cv2.imshow('Guido Van Rossum', img)

cv2.waitKey(0)

cv2.destroyAllWindows()

In [6]:
print(type(face))

<class 'numpy.ndarray'>


In [7]:
print(face)

[[481 154 439 439]
 [140 955  58  58]
 [803 763  78  78]]
