# Computer Vision 📷 📹 🎥

1. `Extract` Information from Image
2. Computer Visualize an Image as a `Matrix` 
3. Each Element of `Matrix` represents is know as `Pixel` of an Image.
4. Each `Pixel` is composed of `3 Channels` R G and B which describes Intensity.
5. Each Channel need `8 Bits` therefor it becomes `24 Bits` for Each Pixel.
    
### Storage Requirements
1. Binary : `1 Bit` Per Pixel
2. Black and White : `8 Bits` Per Pixel | 1 Channel
3. Grayscale : `8 Bits` Per Pixel | 1 Channel
4. Color : `24 Bits` Per Pixel | 3 Channels    

In [1]:
import cv2

Read Image in **RGB** Color

In [2]:
img = cv2.imread('../Image/opencv-logo.png',1)

**Show** Image

In [3]:
cv2.imshow('Image',img)
cv2.waitKey(0)

-1

**Write** Image

In [4]:
cv2.imwrite('../Image/OpenCV.png', img)

True

**Data Type** of Object

In [5]:
type(img)

numpy.ndarray

In [6]:
print(img.shape)
print(f'Matrix of Image has {img.shape[0]} Rows, {img.shape[1]} Columns and {img.shape[2]} Channels')

(739, 600, 3)
Matrix of Image has 739 Rows, 600 Columns and 3 Channels


In [7]:
print(f'Rows : {len(img)}')
print(f'Columns : {len(img[0])}')
print(f'Channels : {len(img[0][0])}')

Rows : 739
Columns : 600
Channels : 3


In [8]:
print(img.dtype) # o to 255

uint8


`Pixel` Value at Specific location

In [9]:
print(img[10,20])

[255 255 255]


`First` Channel

In [10]:
print(img[:,:,0])

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


Rows x Columns x Channels

In [11]:
print(f'Total Number of Pixels : {img.size}') 

Total Number of Pixels : 1330200


`Resize` an Image

In [12]:
small = cv2.resize(img, ((int(img.shape[1]/2)),(int(img.shape[0]/2))))

cv2.imshow('Small',small)

cv2.waitKey(0)

cv2.destroyAllWindows()

In [13]:
cv2.imwrite('../Image/Small.png', small)

True